<script type="text/javascript">

var $selectm = $('#municipio');
    var $selectc = $('#ciudad');

    console.log($selectm);

const temp = [
    {
        "id":0,
        "departamento":"AMAZONAS",
        "ciudades":[
            {"ciudad":"LETICIA"},
                {"ciudad":"PUERTO NARIÑO"}
        ]
    },
    {
        "id":1,
        "departamento":"ANTIOQUIA",
        "ciudades":[
            {"ciudad":"ABEJORRAL"},
            {"ciudad":"ABRIAQUÍ"},
            {"ciudad":"ALEJANDRÍA"},
            {"ciudad":"AMAGÁ"},
            {"ciudad":"AMALFI"},
            {"ciudad":"ANDES"},
            {"ciudad":"ANGELÓPOLIS"},
            {"ciudad":"ANGOSTURA"},
            {"ciudad":"ANORÍ"},
            {"ciudad":"ANZÁ"},
            {"ciudad":"APARTADÓ"},
            {"ciudad":"ARBOLETES"},
            {"ciudad":"ARGELIA"},
            {"ciudad":"ARMENIA"},
            {"ciudad":"BARBOSA"},
            {"ciudad":"BELLO"},
            {"ciudad":"BELMIRA"},
            {"ciudad":"BETANIA"},
            {"ciudad":"BETULIA"},
            {"ciudad":"BRICEÑO"},
            {"ciudad":"BURITICÁ"},
            {"ciudad":"CÁCERES"},
            {"ciudad":"CAICEDO"},
            {"ciudad":"CALDAS"},
            {"ciudad":"CAMPAMENTO"},
            {"ciudad":"CAÑASGORDAS"},
            {"ciudad":"CARACOLÍ"},
            {"ciudad":"CARAMANTA"},
            {"ciudad":"CAREPA"},
            {"ciudad":"CAROLINA DEL PRÍNCIPE"},
            {"ciudad":"CAUCASIA"},
            {"ciudad":"CHIGORODÓ"},
            {"ciudad":"CISNEROS"},
            {"ciudad":"CIUDAD BOLÍVAR"},
            {"ciudad":"COCORNÁ"},
            {"ciudad":"CONCEPCIÓN"},
            {"ciudad":"CONCORDIA"},
            {"ciudad":"COPACABANA"},
            {"ciudad":"DABEIBA"},
            {"ciudad":"DONMATÍAS"},
            {"ciudad":"EBÉJICO"},
            {"ciudad":"EL BAGRE"},
            {"ciudad":"EL CARMEN DE VIBORAL"},
            {"ciudad":"EL PEÑOL"},
            {"ciudad":"EL RETIRO"},
            {"ciudad":"EL SANTUARIO"},
            {"ciudad":"ENTRERRÍOS"},
            {"ciudad":"ENVIGADO"},
            {"ciudad":"FREDONIA"},
            {"ciudad":"FRONTINO"},
            {"ciudad":"GIRALDO"},
            {"ciudad":"GIRARDOTA"},
            {"ciudad":"GÓMEZ PLATA"},
            {"ciudad":"GRANADA"},
            {"ciudad":"GUADALUPE"},
            {"ciudad":"GUARNE"},
            {"ciudad":"GUATAPÉ"},
            {"ciudad":"HELICONIA"},
            {"ciudad":"HISPANIA"},
            {"ciudad":"ITAGÜÍ"},
            {"ciudad":"ITUANGO"},
            {"ciudad":"JARDÍN"},
            {"ciudad":"JERICÓ"},
            {"ciudad":"LA CEJA"},
            {"ciudad":"LA ESTRELLA"},
            {"ciudad":"LA PINTADA"},
            {"ciudad":"LA UNIÓN"},
            {"ciudad":"LIBORINA"},
            {"ciudad":"MACEO"},
            {"ciudad":"MARINILLA"},
            {"ciudad":"MEDELLÍN"},
            {"ciudad":"MONTEBELLO"},
            {"ciudad":"MURINDÓ"},
            {"ciudad":"MUTATÁ"},
            {"ciudad":"NARIÑO"},
            {"ciudad":"NECHÍ"},
            {"ciudad":"NECOCLÍ"},
            {"ciudad":"OLAYA"},
            {"ciudad":"PEQUE"},
            {"ciudad":"PUEBLORRICO"},
            {"ciudad":"PUERTO BERRÍO"},
            {"ciudad":"PUERTO NARE"},
            {"ciudad":"PUERTO TRIUNFO"},
            {"ciudad":"REMEDIOS"},
            {"ciudad":"RIONEGRO"},
            {"ciudad":"SABANALARGA"},
            {"ciudad":"SABANETA"},
            {"ciudad":"SALGAR"},
            {"ciudad":"SAN ANDRÉS DE CUERQUIA"},
            {"ciudad":"SAN CARLOS"},
            {"ciudad":"SAN FRANCISCO"},
            {"ciudad":"SAN JERÓNIMO"},
            {"ciudad":"SAN JOSÉ DE LA MONTAÑA"},
            {"ciudad":"SAN JUAN DE URABÁ"},
            {"ciudad":"SAN LUIS"},
            {"ciudad":"SAN PEDRO DE URABÁ"},
            {"ciudad":"SAN PEDRO DE LOS MILAGROS"},
            {"ciudad":"SAN RAFAEL"},
            {"ciudad":"SAN ROQUE"},
            {"ciudad":"SAN VICENTE"},
            {"ciudad":"SANTA BÁRBARA"},
            {"ciudad":"SANTA FE DE ANTIOQUIA"},
            {"ciudad":"SANTA ROSA DE OSOS"},
            {"ciudad":"SANTO DOMINGO"},
            {"ciudad":"SEGOVIA"},
            {"ciudad":"SONSÓN"},
            {"ciudad":"SOPETRÁN"},
            {"ciudad":"TÁMESIS"},
            {"ciudad":"TARAZÁ"},
            {"ciudad":"TARSO"},
            {"ciudad":"TITIRIBÍ"},
            {"ciudad":"TOLEDO"},
            {"ciudad":"TURBO"},
            {"ciudad":"URAMITA"},
            {"ciudad":"URRAO"},
            {"ciudad":"VALDIVIA"},
            {"ciudad":"VALPARAÍSO"},
            {"ciudad":"VEGACHÍ"},
            {"ciudad":"VENECIA"},
            {"ciudad":"VIGÍA DEL FUERTE"},
            {"ciudad":"YALÍ"},
            {"ciudad":"YARUMAL"},
            {"ciudad":"YOLOMBÓ"},
            {"ciudad":"YONDÓ"},
            {"ciudad":"ZARAGOZA"}
        ]
    },
    {
        "id":2,
        "departamento":"ARAUCA",
        "ciudades":[
            {"ciudad":"ARAUCA"},
            {"ciudad":"ARAUQUITA"},
            {"ciudad":"CRAVO NORTE"},
            {"ciudad":"FORTUL"},
            {"ciudad":"PUERTO RONDÓN"},
            {"ciudad":"SARAVENA"},
            {"ciudad":"TAME"}
        ]
    },
    {
        "id":3,
        "departamento":"ATLÁNTICO",
        "ciudades":[
            {"ciudad":"BARANOA"},
            {"ciudad":"BARRANQUILLA"},
            {"ciudad":"CAMPO DE LA CRUZ"},
            {"ciudad":"CANDELARIA"},
            {"ciudad":"GALAPA"},
            {"ciudad":"JUAN DE ACOSTA"},
            {"ciudad":"LURUACO"},
            {"ciudad":"MALAMBO"},
            {"ciudad":"MANATÍ"},
            {"ciudad":"PALMAR DE VARELA"},
            {"ciudad":"PIOJÓ"},
            {"ciudad":"POLONUEVO"},
            {"ciudad":"PONEDERA"},
            {"ciudad":"PUERTO COLOMBIA"},
            {"ciudad":"REPELÓN"},
            {"ciudad":"SABANAGRANDE"},
            {"ciudad":"SABANALARGA"},
            {"ciudad":"SANTA LUCÍA"},
            {"ciudad":"SANTO TOMÁS"},
            {"ciudad":"SOLEDAD"},
            {"ciudad":"SUÁN"},
            {"ciudad":"TUBARÁ"},
            {"ciudad":"USIACURÍ"}
        ]
    },
    {
        "id":4,
        "departamento":"BOLÍVAR",
        "ciudades":[
            {"ciudad":"ACHÍ"},
            {"ciudad":"ALTOS DEL ROSARIO"},
            {"ciudad":"ARENAL"},
            {"ciudad":"ARJONA"},
            {"ciudad":"ARROYOHONDO"},
            {"ciudad":"BARRANCO DE LOBA"},
            {"ciudad":"BRAZUELO DE PAPAYAL"},
            {"ciudad":"CALAMAR"},
            {"ciudad":"CANTAGALLO"},
            {"ciudad":"CARTAGENA DE INDIAS"},
            {"ciudad":"CICUCO"},
            {"ciudad":"CLEMENCIA"},
            {"ciudad":"CÓRDOBA"},
            {"ciudad":"EL CARMEN DE BOLÍVAR"},
            {"ciudad":"EL GUAMO"},
            {"ciudad":"EL PEÑÓN"},
            {"ciudad":"HATILLO DE LOBA"},
            {"ciudad":"MAGANGUÉ"},
            {"ciudad":"MAHATES"},
            {"ciudad":"MARGARITA"},
            {"ciudad":"MARÍA LA BAJA"},
            {"ciudad":"MOMPÓS"},
            {"ciudad":"MONTECRISTO"},
            {"ciudad":"MORALES"},
            {"ciudad":"NOROSÍ"},
            {"ciudad":"PINILLOS"},
            {"ciudad":"REGIDOR"},
            {"ciudad":"RÍO VIEJO"},
            {"ciudad":"SAN CRISTÓBAL"},
            {"ciudad":"SAN ESTANISLAO"},
            {"ciudad":"SAN FERNANDO"},
            {"ciudad":"SAN JACINTO DEL CAUCA"},
            {"ciudad":"SAN JACINTO"},
            {"ciudad":"SAN JUAN NEPOMUCENO"},
            {"ciudad":"SAN MARTÍN DE LOBA"},
            {"ciudad":"SAN PABLO"},
            {"ciudad":"SANTA CATALINA"},
            {"ciudad":"SANTA ROSA"},
            {"ciudad":"SANTA ROSA DEL SUR"},
            {"ciudad":"SIMITÍ"},
            {"ciudad":"SOPLAVIENTO"},
            {"ciudad":"TALAIGUA NUEVO"},
            {"ciudad":"TIQUISIO"},
            {"ciudad":"TURBACO"},
            {"ciudad":"TURBANÁ"},
            {"ciudad":"VILLANUEVA"},
            {"ciudad":"ZAMBRANO"}
        ]
    },
    {
        "id":5,
        "departamento":"BOYACÁ",
        "ciudades":[
            {"ciudad":"ALMEIDA"},
            {"ciudad":"AQUITANIA"},
            {"ciudad":"ARCABUCO"},
            {"ciudad":"BELÉN"},
            {"ciudad":"BERBEO"},
            {"ciudad":"BETÉITIVA"},
            {"ciudad":"BOAVITA"},
            {"ciudad":"BOYACÁ"},
            {"ciudad":"BRICEÑO"},
            {"ciudad":"BUENAVISTA"},
            {"ciudad":"BUSBANZÁ"},
            {"ciudad":"CALDAS"},
            {"ciudad":"CAMPOHERMOSO"},
            {"ciudad":"CERINZA"},
            {"ciudad":"CHINAVITA"},
            {"ciudad":"CHIQUINQUIRÁ"},
            {"ciudad":"CHÍQUIZA"},
            {"ciudad":"CHISCAS"},
            {"ciudad":"CHITA"},
            {"ciudad":"CHITARAQUE"},
            {"ciudad":"CHIVATÁ"},
            {"ciudad":"CHIVOR"},
            {"ciudad":"CIÉNEGA"},
            {"ciudad":"CÓMBITA"},
            {"ciudad":"COPER"},
            {"ciudad":"CORRALES"},
            {"ciudad":"COVARACHÍA"},
            {"ciudad":"CUBARÁ"},
            {"ciudad":"CUCAITA"},
            {"ciudad":"CUÍTIVA"},
            {"ciudad":"DUITAMA"},
            {"ciudad":"EL COCUY"},
            {"ciudad":"EL ESPINO"},
            {"ciudad":"FIRAVITOBA"},
            {"ciudad":"FLORESTA"},
            {"ciudad":"GACHANTIVÁ"},
            {"ciudad":"GÁMEZA"},
            {"ciudad":"GARAGOA"},
            {"ciudad":"GUACAMAYAS"},
            {"ciudad":"GUATEQUE"},
            {"ciudad":"GUAYATÁ"},
            {"ciudad":"GÜICÁN"},
            {"ciudad":"IZA"},
            {"ciudad":"JENESANO"},
            {"ciudad":"JERICÓ"},
            {"ciudad":"LA CAPILLA"},
            {"ciudad":"LA UVITA"},
            {"ciudad":"LA VICTORIA"},
            {"ciudad":"LABRANZAGRANDE"},
            {"ciudad":"MACANAL"},
            {"ciudad":"MARIPÍ"},
            {"ciudad":"MIRAFLORES"},
            {"ciudad":"MONGUA"},
            {"ciudad":"MONGUÍ"},
            {"ciudad":"MONIQUIRÁ"},
            {"ciudad":"MOTAVITA"},
            {"ciudad":"MUZO"},
            {"ciudad":"NOBSA"},
            {"ciudad":"NUEVO COLÓN"},
            {"ciudad":"OICATÁ"},
            {"ciudad":"OTANCHE"},
            {"ciudad":"PACHAVITA"},
            {"ciudad":"PÁEZ"},
            {"ciudad":"PAIPA"},
            {"ciudad":"PAJARITO"},
            {"ciudad":"PANQUEBA"},
            {"ciudad":"PAUNA"},
            {"ciudad":"PAYA"},
            {"ciudad":"PAZ DEL RÍO"},
            {"ciudad":"PESCA"},
            {"ciudad":"PISBA"},
            {"ciudad":"PUERTO BOYACÁ"},
            {"ciudad":"QUÍPAMA"},
            {"ciudad":"RAMIRIQUÍ"},
            {"ciudad":"RÁQUIRA"},
            {"ciudad":"RONDÓN"},
            {"ciudad":"SABOYÁ"},
            {"ciudad":"SÁCHICA"},
            {"ciudad":"SAMACÁ"},
            {"ciudad":"SAN EDUARDO"},
            {"ciudad":"SAN JOSÉ DE PARE"},
            {"ciudad":"SAN LUIS DE GACENO"},
            {"ciudad":"SAN MATEO"},
            {"ciudad":"SAN MIGUEL DE SEMA"},
            {"ciudad":"SAN PABLO DE BORBUR"},
            {"ciudad":"SANTA MARÍA"},
            {"ciudad":"SANTA ROSA DE VITERBO"},
            {"ciudad":"SANTA SOFÍA"},
            {"ciudad":"SANTANA"},
            {"ciudad":"SATIVANORTE"},
            {"ciudad":"SATIVASUR"},
            {"ciudad":"SIACHOQUE"},
            {"ciudad":"SOATÁ"},
            {"ciudad":"SOCHA"},
            {"ciudad":"SOCOTÁ"},
            {"ciudad":"SOGAMOSO"},
            {"ciudad":"SOMONDOCO"},
            {"ciudad":"SORA"},
            {"ciudad":"SORACÁ"},
            {"ciudad":"SOTAQUIRÁ"},
            {"ciudad":"SUSACÓN"},
            {"ciudad":"SUTAMARCHÁN"},
            {"ciudad":"SUTATENZA"},
            {"ciudad":"TASCO"},
            {"ciudad":"TENZA"},
            {"ciudad":"TIBANÁ"},
            {"ciudad":"TIBASOSA"},
            {"ciudad":"TINJACÁ"},
            {"ciudad":"TIPACOQUE"},
            {"ciudad":"TOCA"},
            {"ciudad":"TOGÜÍ"},
            {"ciudad":"TÓPAGA"},
            {"ciudad":"TOTA"},
            {"ciudad":"TUNJA"},
            {"ciudad":"TUNUNGUÁ"},
            {"ciudad":"TURMEQUÉ"},
            {"ciudad":"TUTA"},
            {"ciudad":"TUTAZÁ"},
            {"ciudad":"ÚMBITA"},
            {"ciudad":"VENTAQUEMADA"},
            {"ciudad":"VILLA DE LEYVA"},
            {"ciudad":"VIRACACHÁ"},
            {"ciudad":"ZETAQUIRA"}
        ]
    },
    {
        "id":6,
        "departamento":"CALDAS",
        "ciudades":[
            {"ciudad":"AGUADAS"},
            {"ciudad":"ANSERMA"},
            {"ciudad":"ARANZAZU"},
            {"ciudad":"BELALCÁZAR"},
            {"ciudad":"CHINCHINÁ"},
            {"ciudad":"FILADELFIA"},
            {"ciudad":"LA DORADA"},
            {"ciudad":"LA MERCED"},
            {"ciudad":"MANIZALES"},
            {"ciudad":"MANZANARES"},
            {"ciudad":"MARMATO"},
            {"ciudad":"MARQUETALIA"},
            {"ciudad":"MARULANDA"},
            {"ciudad":"NEIRA"},
            {"ciudad":"NORCASIA"},
            {"ciudad":"PÁCORA"},
            {"ciudad":"PALESTINA"},
            {"ciudad":"PENSILVANIA"},
            {"ciudad":"RIOSUCIO"},
            {"ciudad":"RISARALDA"},
            {"ciudad":"SALAMINA"},
            {"ciudad":"SAMANÁ"},
            {"ciudad":"SAN JOSÉ"},
            {"ciudad":"SUPÍA"},
            {"ciudad":"VICTORIA"},
            {"ciudad":"VILLAMARÍA"},
            {"ciudad":"VITERBO"}
        ]
    },
    {
        "id":7,
        "departamento":"CAQUETÁ",
        "ciudades":[
            {"ciudad":"ALBANIA"},
            {"ciudad":"BELÉN DE LOS ANDAQUÍES"},
            {"ciudad":"CARTAGENA DEL CHAIRÁ"},
            {"ciudad":"CURILLO"},
            {"ciudad":"EL DONCELLO"},
            {"ciudad":"EL PAUJIL"},
            {"ciudad":"FLORENCIA"},
            {"ciudad":"LA MONTAÑITA"},
            {"ciudad":"MILÁN"},
            {"ciudad":"MORELIA"},
            {"ciudad":"PUERTO RICO"},
            {"ciudad":"SAN JOSÉ DEL FRAGUA"},
            {"ciudad":"SAN VICENTE DEL CAGUÁN"},
            {"ciudad":"SOLANO"},
            {"ciudad":"SOLITA"},
            {"ciudad":"VALPARAÍSO"}
        ]
    },
    {
        "id":8,
        "departamento":"CASANARE",
        "ciudades":[
            {"ciudad":"AGUAZUL"},
            {"ciudad":"CHÁMEZA"},
            {"ciudad":"HATO COROZAL"},
            {"ciudad":"LA SALINA"},
            {"ciudad":"MANÍ"},
            {"ciudad":"MONTERREY"},
            {"ciudad":"NUNCHÍA"},
            {"ciudad":"OROCUÉ"},
            {"ciudad":"PAZ DE ARIPORO"},
            {"ciudad":"PORE"},
            {"ciudad":"RECETOR"},
            {"ciudad":"SABANALARGA"},
            {"ciudad":"SÁCAMA"},
            {"ciudad":"SAN LUIS DE PALENQUE"},
            {"ciudad":"TÁMARA"},
            {"ciudad":"TAURAMENA"},
            {"ciudad":"TRINIDAD"},
            {"ciudad":"VILLANUEVA"},
            {"ciudad":"YOPAL"}
        ]
    },
    {
        "id":9,
        "departamento":"CAUCA",
        "ciudades":[
            {"ciudad":"ALMAGUER"},
            {"ciudad":"ARGELIA"},
            {"ciudad":"BALBOA"},
            {"ciudad":"BOLÍVAR"},
            {"ciudad":"BUENOS AIRES"},
            {"ciudad":"CAJIBÍO"},
            {"ciudad":"CALDONO"},
            {"ciudad":"CALOTO"},
            {"ciudad":"CORINTO"},
            {"ciudad":"EL TAMBO"},
            {"ciudad":"FLORENCIA"},
            {"ciudad":"GUACHENÉ"},
            {"ciudad":"GUAPÍ"},
            {"ciudad":"INZÁ"},
            {"ciudad":"JAMBALÓ"},
            {"ciudad":"LA SIERRA"},
            {"ciudad":"LA VEGA"},
            {"ciudad":"LÓPEZ DE MICAY"},
            {"ciudad":"MERCADERES"},
            {"ciudad":"MIRANDA"},
            {"ciudad":"MORALES"},
            {"ciudad":"PADILLA"},
            {"ciudad":"PÁEZ"},
            {"ciudad":"PATÍA"},
            {"ciudad":"PIAMONTE"},
            {"ciudad":"PIENDAMÓ"},
            {"ciudad":"POPAYÁN"},
            {"ciudad":"PUERTO TEJADA"},
            {"ciudad":"PURACÉ"},
            {"ciudad":"ROSAS"},
            {"ciudad":"SAN SEBASTIÁN"},
            {"ciudad":"SANTA ROSA"},
            {"ciudad":"SANTANDER DE QUILICHAO"},
            {"ciudad":"SILVIA"},
            {"ciudad":"SOTARÁ"},
            {"ciudad":"SUÁREZ"},
            {"ciudad":"SUCRE"},
            {"ciudad":"TIMBÍO"},
            {"ciudad":"TIMBIQUÍ"},
            {"ciudad":"TORIBÍO"},
            {"ciudad":"TOTORÓ"},
            {"ciudad":"VILLA RICA"}
        ]
    },
    {
        "id":10,
        "departamento":"CESAR",
        "ciudades":[
            {"ciudad":"AGUACHICA"},
            {"ciudad":"AGUSTÍN CODAZZI"},
            {"ciudad":"ASTREA"},
            {"ciudad":"BECERRIL"},
            {"ciudad":"BOSCONIA"},
            {"ciudad":"CHIMICHAGUA"},
            {"ciudad":"CHIRIGUANÁ"},
            {"ciudad":"CURUMANÍ"},
            {"ciudad":"EL COPEY"},
            {"ciudad":"EL PASO"},
            {"ciudad":"GAMARRA"},
            {"ciudad":"GONZÁLEZ"},
            {"ciudad":"LA GLORIA (CESAR)"},
            {"ciudad":"LA JAGUA DE IBIRICO"},
            {"ciudad":"LA PAZ"},
            {"ciudad":"MANAURE BALCÓN DEL CESAR"},
            {"ciudad":"PAILITAS"},
            {"ciudad":"PELAYA"},
            {"ciudad":"PUEBLO BELLO"},
            {"ciudad":"RÍO DE ORO"},
            {"ciudad":"SAN ALBERTO"},
            {"ciudad":"SAN DIEGO"},
            {"ciudad":"SAN MARTÍN"},
            {"ciudad":"TAMALAMEQUE"},
            {"ciudad":"VALLEDUPAR"}
        ]
    },
    {
        "id":11,
        "departamento":"CHOCÓ",
        "ciudades":[
            {"ciudad":"ACANDÍ"},
            {"ciudad":"ALTO BAUDÓ"},
            {"ciudad":"BAGADÓ"},
            {"ciudad":"BAHÍA SOLANO"},
            {"ciudad":"BAJO BAUDÓ"},
            {"ciudad":"BOJAYÁ"},
            {"ciudad":"CANTÓN DE SAN PABLO"},
            {"ciudad":"CÉRTEGUI"},
            {"ciudad":"CONDOTO"},
            {"ciudad":"EL ATRATO"},
            {"ciudad":"EL CARMEN DE ATRATO"},
            {"ciudad":"EL CARMEN DEL DARIÉN"},
            {"ciudad":"ISTMINA"},
            {"ciudad":"JURADÓ"},
            {"ciudad":"LITORAL DE SAN JUAN"},
            {"ciudad":"LLORÓ"},
            {"ciudad":"MEDIO ATRATO"},
            {"ciudad":"MEDIO BAUDÓ"},
            {"ciudad":"MEDIO SAN JUAN"},
            {"ciudad":"NÓVITA"},
            {"ciudad":"NUQUÍ"},
            {"ciudad":"QUIBDÓ"},
            {"ciudad":"RÍO IRÓ"},
            {"ciudad":"RÍO QUITO"},
            {"ciudad":"RIOSUCIO"},
            {"ciudad":"SAN JOSÉ DEL PALMAR"},
            {"ciudad":"SIPÍ"},
            {"ciudad":"TADÓ"},
            {"ciudad":"UNIÓN PANAMERICANA"},
            {"ciudad":"UNGUÍA"}
        ]
    },
    {
        "id":12,
        "departamento":"CUNDINAMARCA",
        "ciudades":[
            {"ciudad":"AGUA DE DIOS"},
            {"ciudad":"ALBÁN"},
            {"ciudad":"ANAPOIMA"},
            {"ciudad":"ANOLAIMA"},
            {"ciudad":"APULO"},
            {"ciudad":"ARBELÁEZ"},
            {"ciudad":"BELTRÁN"},
            {"ciudad":"BITUIMA"},
            {"ciudad":"BOGOTÁ"},
            {"ciudad":"BOJACÁ"},
            {"ciudad":"CABRERA"},
            {"ciudad":"CACHIPAY"},
            {"ciudad":"CAJICÁ"},
            {"ciudad":"CAPARRAPÍ"},
            {"ciudad":"CÁQUEZA"},
            {"ciudad":"CARMEN DE CARUPA"},
            {"ciudad":"CHAGUANÍ"},
            {"ciudad":"CHÍA"},
            {"ciudad":"CHIPAQUE"},
            {"ciudad":"CHOACHÍ"},
            {"ciudad":"CHOCONTÁ"},
            {"ciudad":"COGUA"},
            {"ciudad":"COTA"},
            {"ciudad":"CUCUNUBÁ"},
            {"ciudad":"EL COLEGIO"},
            {"ciudad":"EL PEÑÓN"},
            {"ciudad":"EL ROSAL"},
            {"ciudad":"FACATATIVÁ"},
            {"ciudad":"FÓMEQUE"},
            {"ciudad":"FOSCA"},
            {"ciudad":"FUNZA"},
            {"ciudad":"FÚQUENE"},
            {"ciudad":"FUSAGASUGÁ"},
            {"ciudad":"GACHALÁ"},
            {"ciudad":"GACHANCIPÁ"},
            {"ciudad":"GACHETÁ"},
            {"ciudad":"GAMA"},
            {"ciudad":"GIRARDOT"},
            {"ciudad":"GRANADA"},
            {"ciudad":"GUACHETÁ"},
            {"ciudad":"GUADUAS"},
            {"ciudad":"GUASCA"},
            {"ciudad":"GUATAQUÍ"},
            {"ciudad":"GUATAVITA"},
            {"ciudad":"GUAYABAL DE SÍQUIMA"},
            {"ciudad":"GUAYABETAL"},
            {"ciudad":"GUTIÉRREZ"},
            {"ciudad":"JERUSALÉN"},
            {"ciudad":"JUNÍN"},
            {"ciudad":"LA CALERA"},
            {"ciudad":"LA MESA"},
            {"ciudad":"LA PALMA"},
            {"ciudad":"LA PEÑA"},
            {"ciudad":"LA VEGA"},
            {"ciudad":"LENGUAZAQUE"},
            {"ciudad":"MACHETÁ"},
            {"ciudad":"MADRID"},
            {"ciudad":"MANTA"},
            {"ciudad":"MEDINA"},
            {"ciudad":"MOSQUERA"},
            {"ciudad":"NARIÑO"},
            {"ciudad":"NEMOCÓN"},
            {"ciudad":"NILO"},
            {"ciudad":"NIMAIMA"},
            {"ciudad":"NOCAIMA"},
            {"ciudad":"PACHO"},
            {"ciudad":"PAIME"},
            {"ciudad":"PANDI"},
            {"ciudad":"PARATEBUENO"},
            {"ciudad":"PASCA"},
            {"ciudad":"PUERTO SALGAR"},
            {"ciudad":"PULÍ"},
            {"ciudad":"QUEBRADANEGRA"},
            {"ciudad":"QUETAME"},
            {"ciudad":"QUIPILE"},
            {"ciudad":"RICAURTE"},
            {"ciudad":"SAN ANTONIO DEL TEQUENDAMA"},
            {"ciudad":"SAN BERNARDO"},
            {"ciudad":"SAN CAYETANO"},
            {"ciudad":"SAN FRANCISCO"},
            {"ciudad":"SAN JUAN DE RIOSECO"},
            {"ciudad":"SASAIMA"},
            {"ciudad":"SESQUILÉ"},
            {"ciudad":"SIBATÉ"},
            {"ciudad":"SILVANIA"},
            {"ciudad":"SIMIJACA"},
            {"ciudad":"SOACHA"},
            {"ciudad":"SOPÓ"},
            {"ciudad":"SUBACHOQUE"},
            {"ciudad":"SUESCA"},
            {"ciudad":"SUPATÁ"},
            {"ciudad":"SUSA"},
            {"ciudad":"SUTATAUSA"},
            {"ciudad":"TABIO"},
            {"ciudad":"TAUSA"},
            {"ciudad":"TENA"},
            {"ciudad":"TENJO"},
            {"ciudad":"TIBACUY"},
            {"ciudad":"TIBIRITA"},
            {"ciudad":"TOCAIMA"},
            {"ciudad":"TOCANCIPÁ"},
            {"ciudad":"TOPAIPÍ"},
            {"ciudad":"UBALÁ"},
            {"ciudad":"UBAQUE"},
            {"ciudad":"UBATÉ"},
            {"ciudad":"UNE"},
            {"ciudad":"ÚTICA"},
            {"ciudad":"VENECIA"},
            {"ciudad":"VERGARA"},
            {"ciudad":"VIANÍ"},
            {"ciudad":"VILLAGÓMEZ"},
            {"ciudad":"VILLAPINZÓN"},
            {"ciudad":"VILLETA"},
            {"ciudad":"VIOTÁ"},
            {"ciudad":"YACOPÍ"},
            {"ciudad":"ZIPACÓN"},
            {"ciudad":"ZIPAQUIRÁ"}
        ]
    },
    {
        "id":13,
        "departamento":"CÓRDOBA",
        "ciudades":[
            {"ciudad":"AYAPEL"},
            {"ciudad":"BUENAVISTA"},
            {"ciudad":"CANALETE"},
            {"ciudad":"CERETÉ"},
            {"ciudad":"CHIMÁ"},
            {"ciudad":"CHINÚ"},
            {"ciudad":"CIÉNAGA DE ORO"},
            {"ciudad":"COTORRA"},
            {"ciudad":"LA APARTADA"},
            {"ciudad":"LORICA"},
            {"ciudad":"LOS CÓRDOBAS"},
            {"ciudad":"MOMIL"},
            {"ciudad":"MONTELÍBANO"},
            {"ciudad":"MONTERÍA"},
            {"ciudad":"MOÑITOS"},
            {"ciudad":"PLANETA RICA"},
            {"ciudad":"PUEBLO NUEVO"},
            {"ciudad":"PUERTO ESCONDIDO"},
            {"ciudad":"PUERTO LIBERTADOR"},
            {"ciudad":"PURÍSIMA"},
            {"ciudad":"SAHAGÚN"},
            {"ciudad":"SAN ANDRÉS DE SOTAVENTO"},
            {"ciudad":"SAN ANTERO"},
            {"ciudad":"SAN BERNARDO DEL VIENTO"},
            {"ciudad":"SAN CARLOS"},
            {"ciudad":"SAN JOSÉ DE URÉ"},
            {"ciudad":"SAN PELAYO"},
            {"ciudad":"TIERRALTA"},
            {"ciudad":"TUCHÍN"},
            {"ciudad":"VALENCIA"}
        ]
    },
    {
        "id":14,
        "departamento":"GUAINÍA",
        "ciudades":[
            {"ciudad":"INÍRIDA"}
        ]
    },
    {
        "id":15,
        "departamento":"GUAVIARE",
        "ciudades":[
            {"ciudad":"CALAMAR"},
            {"ciudad":"EL RETORNO"},
            {"ciudad":"MIRAFLORES"},
            {"ciudad":"SAN JOSÉ DEL GUAVIARE"}
        ]
    },
    {
        "id":16,
        "departamento":"HUILA",
        "ciudades":[
            {"ciudad":"ACEVEDO"},
            {"ciudad":"AGRADO"},
            {"ciudad":"AIPE"},
            {"ciudad":"ALGECIRAS"},
            {"ciudad":"ALTAMIRA"},
            {"ciudad":"BARAYA"},
            {"ciudad":"CAMPOALEGRE"},
            {"ciudad":"COLOMBIA"},
            {"ciudad":"EL PITAL"},
            {"ciudad":"ELÍAS"},
            {"ciudad":"GARZÓN"},
            {"ciudad":"GIGANTE"},
            {"ciudad":"GUADALUPE"},
            {"ciudad":"HOBO"},
            {"ciudad":"ÍQUIRA"},
            {"ciudad":"ISNOS"},
            {"ciudad":"LA ARGENTINA"},
            {"ciudad":"LA PLATA"},
            {"ciudad":"NÁTAGA"},
            {"ciudad":"NEIVA"},
            {"ciudad":"OPORAPA"},
            {"ciudad":"PAICOL"},
            {"ciudad":"PALERMO"},
            {"ciudad":"PALESTINA"},
            {"ciudad":"PITALITO"},
            {"ciudad":"RIVERA"},
            {"ciudad":"SALADOBLANCO"},
            {"ciudad":"SAN AGUSTÍN"},
            {"ciudad":"SANTA MARÍA"},
            {"ciudad":"SUAZA"},
            {"ciudad":"TARQUI"},
            {"ciudad":"TELLO"},
            {"ciudad":"TERUEL"},
            {"ciudad":"TESALIA"},
            {"ciudad":"TIMANÁ"},
            {"ciudad":"VILLAVIEJA"},
            {"ciudad":"YAGUARÁ"}
        ]
    },
    {
        "id":17,
        "departamento":"LA GUAJIRA",
        "ciudades":[
            {"ciudad":"ALBANIA"},
            {"ciudad":"BARRANCAS"},
            {"ciudad":"DIBULLA"},
            {"ciudad":"DISTRACCIÓN"},
            {"ciudad":"EL MOLINO"},
            {"ciudad":"FONSECA"},
            {"ciudad":"HATONUEVO"},
            {"ciudad":"LA JAGUA DEL PILAR"},
            {"ciudad":"MAICAO"},
            {"ciudad":"MANAURE"},
            {"ciudad":"RIOHACHA"},
            {"ciudad":"SAN JUAN DEL CESAR"},
            {"ciudad":"URIBIA"},
            {"ciudad":"URUMITA"},
            {"ciudad":"VILLANUEVA"}
        ]
    },
    {
        "id":18,
        "departamento":"MAGDALENA",
        "ciudades":[
            {"ciudad":"ALGARROBO"},
            {"ciudad":"ARACATACA"},
            {"ciudad":"ARIGUANÍ"},
            {"ciudad":"CERRO DE SAN ANTONIO"},
            {"ciudad":"CHIBOLO"},
            {"ciudad":"CHIBOLO"},
            {"ciudad":"CIÉNAGA"},
            {"ciudad":"CONCORDIA"},
            {"ciudad":"EL BANCO"},
            {"ciudad":"EL PIÑÓN"},
            {"ciudad":"EL RETÉN"},
            {"ciudad":"FUNDACIÓN"},
            {"ciudad":"GUAMAL"},
            {"ciudad":"NUEVA GRANADA"},
            {"ciudad":"PEDRAZA"},
            {"ciudad":"PIJIÑO DEL CARMEN"},
            {"ciudad":"PIVIJAY"},
            {"ciudad":"PLATO"},
            {"ciudad":"PUEBLO VIEJO"},
            {"ciudad":"REMOLINO"},
            {"ciudad":"SABANAS DE SAN ÁNGEL"},
            {"ciudad":"SALAMINA"},
            {"ciudad":"SAN SEBASTIÁN DE BUENAVISTA"},
            {"ciudad":"SAN ZENÓN"},
            {"ciudad":"SANTA ANA"},
            {"ciudad":"SANTA BÁRBARA DE PINTO"},
            {"ciudad":"SANTA MARTA"},
            {"ciudad":"SITIONUEVO"},
            {"ciudad":"TENERIFE"},
            {"ciudad":"ZAPAYÁN"},
            {"ciudad":"ZONA BANANERA"}
        ]
    },
    {
        "id":19,
        "departamento":"META",
        "ciudades":[
            {"ciudad":"ACACÍAS"},
            {"ciudad":"BARRANCA DE UPÍA"},
            {"ciudad":"CABUYARO"},
            {"ciudad":"CASTILLA LA NUEVA"},
            {"ciudad":"CUBARRAL"},
            {"ciudad":"CUMARAL"},
            {"ciudad":"EL CALVARIO"},
            {"ciudad":"EL CASTILLO"},
            {"ciudad":"EL DORADO"},
            {"ciudad":"FUENTE DE ORO"},
            {"ciudad":"GRANADA"},
            {"ciudad":"GUAMAL"},
            {"ciudad":"LA MACARENA"},
            {"ciudad":"LA URIBE"},
            {"ciudad":"LEJANÍAS"},
            {"ciudad":"MAPIRIPÁN"},
            {"ciudad":"MESETAS"},
            {"ciudad":"PUERTO CONCORDIA"},
            {"ciudad":"PUERTO GAITÁN"},
            {"ciudad":"PUERTO LLERAS"},
            {"ciudad":"PUERTO LÓPEZ"},
            {"ciudad":"PUERTO RICO"},
            {"ciudad":"RESTREPO"},
            {"ciudad":"SAN CARLOS DE GUAROA"},
            {"ciudad":"SAN JUAN DE ARAMA"},
            {"ciudad":"SAN JUANITO"},
            {"ciudad":"SAN MARTÍN"},
            {"ciudad":"VILLAVICENCIO"},
            {"ciudad":"VISTA HERMOSA"}
        ]
    },
    {
        "id":20,
        "departamento":"NARIÑO",
        "ciudades":[
            {"ciudad":"ALDANA"},
            {"ciudad":"ANCUYÁ"},
            {"ciudad":"ARBOLEDA"},
            {"ciudad":"BARBACOAS"},
            {"ciudad":"BELÉN"},
            {"ciudad":"BUESACO"},
            {"ciudad":"CHACHAGÜÍ"},
            {"ciudad":"COLÓN"},
            {"ciudad":"CONSACÁ"},
            {"ciudad":"CONTADERO"},
            {"ciudad":"CÓRDOBA"},
            {"ciudad":"CUASPUD"},
            {"ciudad":"CUMBAL"},
            {"ciudad":"CUMBITARA"},
            {"ciudad":"EL CHARCO"},
            {"ciudad":"EL PEÑOL"},
            {"ciudad":"EL ROSARIO"},
            {"ciudad":"EL TABLÓN"},
            {"ciudad":"EL TAMBO"},
            {"ciudad":"FRANCISCO PIZARRO"},
            {"ciudad":"FUNES"},
            {"ciudad":"GUACHUCAL"},
            {"ciudad":"GUAITARILLA"},
            {"ciudad":"GUALMATÁN"},
            {"ciudad":"ILES"},
            {"ciudad":"IMUÉS"},
            {"ciudad":"IPIALES"},
            {"ciudad":"LA CRUZ"},
            {"ciudad":"LA FLORIDA"},
            {"ciudad":"LA LLANADA"},
            {"ciudad":"LA TOLA"},
            {"ciudad":"LA UNIÓN"},
            {"ciudad":"LEIVA"},
            {"ciudad":"LINARES"},
            {"ciudad":"LOS ANDES"},
            {"ciudad":"MAGÜÍ PAYÁN"},
            {"ciudad":"MALLAMA"},
            {"ciudad":"MOSQUERA"},
            {"ciudad":"NARIÑO"},
            {"ciudad":"OLAYA HERRERA"},
            {"ciudad":"OSPINA"},
            {"ciudad":"PASTO"},
            {"ciudad":"POLICARPA"},
            {"ciudad":"POTOSÍ"},
            {"ciudad":"PROVIDENCIA"},
            {"ciudad":"PUERRES"},
            {"ciudad":"PUPIALES"},
            {"ciudad":"RICAURTE"},
            {"ciudad":"ROBERTO PAYÁN"},
            {"ciudad":"SAMANIEGO"},
            {"ciudad":"SAN BERNARDO"},
            {"ciudad":"SAN JOSÉ DE ALBÁN"},
            {"ciudad":"SAN LORENZO"},
            {"ciudad":"SAN PABLO"},
            {"ciudad":"SAN PEDRO DE CARTAGO"},
            {"ciudad":"SANDONÁ"},
            {"ciudad":"SANTA BÁRBARA"},
            {"ciudad":"SANTACRUZ"},
            {"ciudad":"SAPUYES"},
            {"ciudad":"TAMINANGO"},
            {"ciudad":"TANGUA"},
            {"ciudad":"TUMACO"},
            {"ciudad":"TÚQUERRES"},
            {"ciudad":"YACUANQUER"}
        ]
    },
    {
        "id":21,
        "departamento":"NORTE DE SANTANDER",
        "ciudades":[
            {"ciudad":"ÁBREGO"},
            {"ciudad":"ARBOLEDAS"},
            {"ciudad":"BOCHALEMA"},
            {"ciudad":"BUCARASICA"},
            {"ciudad":"CÁCHIRA"},
            {"ciudad":"CÁCOTA"},
            {"ciudad":"CHINÁCOTA"},
            {"ciudad":"CHITAGÁ"},
            {"ciudad":"CONVENCIÓN"},
            {"ciudad":"CÚCUTA"},
            {"ciudad":"CUCUTILLA"},
            {"ciudad":"DURANÍA"},
            {"ciudad":"EL CARMEN"},
            {"ciudad":"EL TARRA"},
            {"ciudad":"EL ZULIA"},
            {"ciudad":"GRAMALOTE"},
            {"ciudad":"HACARÍ"},
            {"ciudad":"HERRÁN"},
            {"ciudad":"LA ESPERANZA"},
            {"ciudad":"LA PLAYA DE BELÉN"},
            {"ciudad":"LABATECA"},
            {"ciudad":"LOS PATIOS"},
            {"ciudad":"LOURDES"},
            {"ciudad":"MUTISCUA"},
            {"ciudad":"OCAÑA"},
            {"ciudad":"PAMPLONA"},
            {"ciudad":"PAMPLONITA"},
            {"ciudad":"PUERTO SANTANDER"},
            {"ciudad":"RAGONVALIA"},
            {"ciudad":"SALAZAR DE LAS PALMAS"},
            {"ciudad":"SAN CALIXTO"},
            {"ciudad":"SAN CAYETANO"},
            {"ciudad":"SANTIAGO"},
            {"ciudad":"SANTO DOMINGO DE SILOS"},
            {"ciudad":"SARDINATA"},
            {"ciudad":"TEORAMA"},
            {"ciudad":"TIBÚ"},
            {"ciudad":"TOLEDO"},
            {"ciudad":"VILLA CARO"},
            {"ciudad":"VILLA DEL ROSARIO"}
        ]
    },
    {
        "id":22,
        "departamento":"PUTUMAYO",
        "ciudades":[
            {"ciudad":"COLÓN"},
            {"ciudad":"MOCOA"},
            {"ciudad":"ORITO"},
            {"ciudad":"PUERTO ASÍS"},
            {"ciudad":"PUERTO CAICEDO"},
            {"ciudad":"PUERTO GUZMÁN"},
            {"ciudad":"PUERTO LEGUÍZAMO"},
            {"ciudad":"SAN FRANCISCO"},
            {"ciudad":"SAN MIGUEL"},
            {"ciudad":"SANTIAGO"},
            {"ciudad":"SIBUNDOY"},
            {"ciudad":"VALLE DEL GUAMUEZ"},
            {"ciudad":"VILLAGARZÓN"}
        ]
    },
    {
        "id":23,
        "departamento":"QUINDÍO",
        "ciudades":[
            {"ciudad":"ARMENIA"},
            {"ciudad":"BUENAVISTA"},
            {"ciudad":"CALARCÁ"},
            {"ciudad":"CIRCASIA"},
            {"ciudad":"CÓRDOBA"},
            {"ciudad":"FILANDIA"},
            {"ciudad":"GÉNOVA"},
            {"ciudad":"LA TEBAIDA"},
            {"ciudad":"MONTENEGRO"},
            {"ciudad":"PIJAO"},
            {"ciudad":"QUIMBAYA"},
            {"ciudad":"SALENTO"}
        ]
    },
    {
        "id":24,
        "departamento":"RISARALDA",
        "ciudades":[
            {"ciudad":"APÍA"},
            {"ciudad":"BALBOA"},
            {"ciudad":"BELÉN DE UMBRÍA"},
            {"ciudad":"DOSQUEBRADAS"},
            {"ciudad":"GUÁTICA"},
            {"ciudad":"LA CELIA"},
            {"ciudad":"LA VIRGINIA"},
            {"ciudad":"MARSELLA"},
            {"ciudad":"MISTRATÓ"},
            {"ciudad":"PEREIRA"},
            {"ciudad":"PUEBLO RICO"},
            {"ciudad":"QUINCHÍA"},
            {"ciudad":"SANTA ROSA DE CABAL"},
            {"ciudad":"SANTUARIO"}
        ]
    },
    {
        "id":25,
        "departamento":"SAN ANDRÉS Y PROVIDENCIA",
        "ciudades":[
            {"ciudad":"PROVIDENCIA Y SANTA CATALINA ISLAS"},
            {"ciudad":"SAN ANDRÉS"}
        ]
    },
    {
        "id":26,
        "departamento":"SANTANDER",
        "ciudades":[
            {"ciudad":"AGUADA"},
            {"ciudad":"ALBANIA"},
            {"ciudad":"ARATOCA"},
            {"ciudad":"BARBOSA"},
            {"ciudad":"BARICHARA"},
            {"ciudad":"BARRANCABERMEJA"},
            {"ciudad":"BETULIA"},
            {"ciudad":"BOLÍVAR"},
            {"ciudad":"BUCARAMANGA"},
            {"ciudad":"CABRERA"},
            {"ciudad":"CALIFORNIA"},
            {"ciudad":"CAPITANEJO"},
            {"ciudad":"CARCASÍ"},
            {"ciudad":"CEPITÁ"},
            {"ciudad":"CERRITO"},
            {"ciudad":"CHARALÁ"},
            {"ciudad":"CHARTA"},
            {"ciudad":"CHIMA"},
            {"ciudad":"CHIPATÁ"},
            {"ciudad":"CIMITARRA"},
            {"ciudad":"CONCEPCIÓN"},
            {"ciudad":"CONFINES"},
            {"ciudad":"CONTRATACIÓN"},
            {"ciudad":"COROMORO"},
            {"ciudad":"CURITÍ"},
            {"ciudad":"EL CARMEN DE CHUCURÍ"},
            {"ciudad":"EL GUACAMAYO"},
            {"ciudad":"EL PEÑÓN"},
            {"ciudad":"EL PLAYÓN"},
            {"ciudad":"EL SOCORRO"},
            {"ciudad":"ENCINO"},
            {"ciudad":"ENCISO"},
            {"ciudad":"FLORIÁN"},
            {"ciudad":"FLORIDABLANCA"},
            {"ciudad":"GALÁN"},
            {"ciudad":"GÁMBITA"},
            {"ciudad":"GIRÓN"},
            {"ciudad":"GUACA"},
            {"ciudad":"GUADALUPE"},
            {"ciudad":"GUAPOTÁ"},
            {"ciudad":"GUAVATÁ"},
            {"ciudad":"GÜEPSA"},
            {"ciudad":"HATO"},
            {"ciudad":"JESÚS MARÍA"},
            {"ciudad":"JORDÁN"},
            {"ciudad":"LA BELLEZA"},
            {"ciudad":"LA PAZ"},
            {"ciudad":"LANDÁZURI"},
            {"ciudad":"LEBRIJA"},
            {"ciudad":"LOS SANTOS"},
            {"ciudad":"MACARAVITA"},
            {"ciudad":"MÁLAGA"},
            {"ciudad":"MATANZA"},
            {"ciudad":"MOGOTES"},
            {"ciudad":"MOLAGAVITA"},
            {"ciudad":"OCAMONTE"},
            {"ciudad":"OIBA"},
            {"ciudad":"ONZAGA"},
            {"ciudad":"PALMAR"},
            {"ciudad":"PALMAS DEL SOCORRO"},
            {"ciudad":"PÁRAMO"},
            {"ciudad":"PIEDECUESTA"},
            {"ciudad":"PINCHOTE"},
            {"ciudad":"PUENTE NACIONAL"},
            {"ciudad":"PUERTO PARRA"},
            {"ciudad":"PUERTO WILCHES"},
            {"ciudad":"RIONEGRO"},
            {"ciudad":"SABANA DE TORRES"},
            {"ciudad":"SAN ANDRÉS"},
            {"ciudad":"SAN BENITO"},
            {"ciudad":"SAN GIL"},
            {"ciudad":"SAN JOAQUÍN"},
            {"ciudad":"SAN JOSÉ DE MIRANDA"},
            {"ciudad":"SAN MIGUEL"},
            {"ciudad":"SAN VICENTE DE CHUCURÍ"},
            {"ciudad":"SANTA BÁRBARA"},
            {"ciudad":"SANTA HELENA DEL OPÓN"},
            {"ciudad":"SIMACOTA"},
            {"ciudad":"SUAITA"},
            {"ciudad":"SUCRE"},
            {"ciudad":"SURATÁ"},
            {"ciudad":"TONA"},
            {"ciudad":"VALLE DE SAN JOSÉ"},
            {"ciudad":"VÉLEZ"},
            {"ciudad":"VETAS"},
            {"ciudad":"VILLANUEVA"},
            {"ciudad":"ZAPATOCA"}
        ]
    },
    
    {
        "id":27,
        "departamento":"SUCRE",
        "ciudades":[
            {"ciudad":"BUENAVISTA"},
            {"ciudad":"CAIMITO"},
            {"ciudad":"CHALÁN"},
            {"ciudad":"COLOSÓ"},
            {"ciudad":"COROZAL"},
            {"ciudad":"COVEÑAS"},
            {"ciudad":"EL ROBLE"},
            {"ciudad":"GALERAS"},
            {"ciudad":"GUARANDA"},
            {"ciudad":"LA UNIÓN"},
            {"ciudad":"LOS PALMITOS"},
            {"ciudad":"MAJAGUAL"},
            {"ciudad":"MORROA"},
            {"ciudad":"OVEJAS"},
            {"ciudad":"SAMPUÉS"},
            {"ciudad":"SAN ANTONIO DE PALMITO"},
            {"ciudad":"SAN BENITO ABAD"},
            {"ciudad":"SAN JUAN DE BETULIA"},
            {"ciudad":"SAN MARCOS"},
            {"ciudad":"SAN ONOFRE"},
            {"ciudad":"SAN PEDRO"},
            {"ciudad":"SINCÉ"},
            {"ciudad":"SINCELEJO"},
            {"ciudad":"SUCRE"},
            {"ciudad":"TOLÚ"},
            {"ciudad":"TOLÚ VIEJO"}
        ]
    },
    {
        "id":28,
        "departamento":"TOLIMA",
        "ciudades":[
            {"ciudad":"ALPUJARRA"},
            {"ciudad":"ALVARADO"},
            {"ciudad":"AMBALEMA"},
            {"ciudad":"ANZOÁTEGUI"},
            {"ciudad":"ARMERO"},
            {"ciudad":"ATACO"},
            {"ciudad":"CAJAMARCA"},
            {"ciudad":"CARMEN DE APICALÁ"},
            {"ciudad":"CASABIANCA"},
            {"ciudad":"CHAPARRAL"},
            {"ciudad":"COELLO"},
            {"ciudad":"COYAIMA"},
            {"ciudad":"CUNDAY"},
            {"ciudad":"DOLORES"},
            {"ciudad":"EL ESPINAL"},
            {"ciudad":"FALÁN"},
            {"ciudad":"FLANDES"},
            {"ciudad":"FRESNO"},
            {"ciudad":"GUAMO"},
            {"ciudad":"HERVEO"},
            {"ciudad":"HONDA"},
            {"ciudad":"IBAGUÉ"},
            {"ciudad":"ICONONZO"},
            {"ciudad":"LÉRIDA"},
            {"ciudad":"LÍBANO"},
            {"ciudad":"MARIQUITA"},
            {"ciudad":"MELGAR"},
            {"ciudad":"MURILLO"},
            {"ciudad":"NATAGAIMA"},
            {"ciudad":"ORTEGA"},
            {"ciudad":"PALOCABILDO"},
            {"ciudad":"PIEDRAS"},
            {"ciudad":"PLANADAS"},
            {"ciudad":"PRADO"},
            {"ciudad":"PURIFICACIÓN"},
            {"ciudad":"RIOBLANCO"},
            {"ciudad":"RONCESVALLES"},
            {"ciudad":"ROVIRA"},
            {"ciudad":"SALDAÑA"},
            {"ciudad":"SAN ANTONIO"},
            {"ciudad":"SAN LUIS"},
            {"ciudad":"SANTA ISABEL"},
            {"ciudad":"SUÁREZ"},
            {"ciudad":"VALLE DE SAN JUAN"},
            {"ciudad":"VENADILLO"},
            {"ciudad":"VILLAHERMOSA"},
            {"ciudad":"VILLARRICA"}
        ]
    },
    {
        "id":29,
        "departamento":"VALLE DEL CAUCA",
        "ciudades":[
            {"ciudad":"ALCALÁ"},
            {"ciudad":"ANDALUCÍA"},
            {"ciudad":"ANSERMANUEVO"},
            {"ciudad":"ARGELIA"},
            {"ciudad":"BOLÍVAR"},
            {"ciudad":"BUENAVENTURA"},
            {"ciudad":"BUGA"},
            {"ciudad":"BUGALAGRANDE"},
            {"ciudad":"CAICEDONIA"},
            {"ciudad":"CALI"},
            {"ciudad":"CALIMA"},
            {"ciudad":"CANDELARIA"},
            {"ciudad":"CARTAGO"},
            {"ciudad":"DAGUA"},
            {"ciudad":"EL ÁGUILA"},
            {"ciudad":"EL CAIRO"},
            {"ciudad":"EL CERRITO"},
            {"ciudad":"EL DOVIO"},
            {"ciudad":"FLORIDA"},
            {"ciudad":"GINEBRA"},
            {"ciudad":"GUACARÍ"},
            {"ciudad":"JAMUNDÍ"},
            {"ciudad":"LA CUMBRE"},
            {"ciudad":"LA UNIÓN"},
            {"ciudad":"LA VICTORIA"},
            {"ciudad":"OBANDO"},
            {"ciudad":"PALMIRA"},
            {"ciudad":"PRADERA"},
            {"ciudad":"RESTREPO"},
            {"ciudad":"RIOFRÍO"},
            {"ciudad":"ROLDANILLO"},
            {"ciudad":"SAN PEDRO"},
            {"ciudad":"SEVILLA"},
            {"ciudad":"TORO"},
            {"ciudad":"TRUJILLO"},
            {"ciudad":"TULUÁ"},
            {"ciudad":"ULLOA"},
            {"ciudad":"VERSALLES"},
            {"ciudad":"VIJES"},
            {"ciudad":"YOTOCO"},
            {"ciudad":"YUMBO"},
            {"ciudad":"ZARZAL"}
        ]
    },
    {
        "id":30,
        "departamento":"VAUPÉS",
        "ciudades":[
            {"ciudad":"CARURÚ"},
                {"ciudad":"MITÚ"},
                    {"ciudad":"TARAIRA"}
        ]
    },
    {
        "id":31,
        "departamento":"VICHADA",
        "ciudades":[
            {"ciudad":"CUMARIBO"},
            {"ciudad":"LA PRIMAVERA"},
            {"ciudad":"PUERTO CARREÑO"},
            {"ciudad":"SANTA ROSALÍA"}
        ]
    }

];





    $(document).ready(function() {

 temp;


post_municipios();




    //alert(options);

/*
    $.each(temp}, function(id}, departamento}, ciudades) {
      $selectc.append('<option value=' + ciudades + '>' + ciudades + '</option>');

    }); */

    //console.log(temp);

  });



  function post_municipios() {
    $.each(temp, function(id, departamento) {
      $selectm.append('<option value=' + departamento.departamento + '>' + departamento.departamento + '</option>');

    });

  }




function ShowSelected()
{


/* Para obtener el valor */
var cod = document.getElementById("municipio").value;
//console.log(temp);

var rest = temp.find(element => element.departamento == cod);
var re = rest.ciudades;

/* console.log(cod);
console.log(rest); */
console.log(re);
console.log(temp);



//console.log(rest.ciudades);

$.each(re, function( id, ciudad) {
      $selectc.append('<option value=' + ciudad.ciudad + '>' + ciudad.ciudad + '</option>');

    });

    $.each(re, function (i, item) {
    $('#mySelect').append($('<option>', {
        value: item.value,
        text : item.text
    }));
});



/* for (const ciudad of temp) {
        let ciudadDb = await Ciudad.findOne({identificacion: ciudad.cedula})
        //console.log(usuarioDb)
        console.log(contador1+=1}, ciudadTotal1 );

    }
  */

/*  Para obtener el texto
var combo = document.getElementByid("municipio");
var selected = combo.options[combo.selectedIndex].text;
alert(selected);*/
}





  /* console.log("cod");
  console.log(cod); */



	</script>
